#!/bin/bash

wget -O epey1.html https://www.epey.com/bisiklet/1 &
wget -O epey2.html https://www.epey.com/bisiklet/2 &
wget -O epey3.html https://www.epey.com/bisiklet/3 &
wget -O epey4.html https://www.epey.com/bisiklet/4 &
wget -O epey5.html https://www.epey.com/bisiklet/5 &
wget -O epey6.html https://www.epey.com/bisiklet/6 &
wget -O epey7.html https://www.epey.com/bisiklet/7 &
wget -O epey8.html https://www.epey.com/bisiklet/8 &
wget -O epey9.html https://www.epey.com/bisiklet/9 &
wget -O epey10.html https://www.epey.com/bisiklet/10 &
wget -O epey11.html https://www.epey.com/bisiklet/11 &
wget -O epey12.html https://www.epey.com/bisiklet/12 &
wget -O epey13.html https://www.epey.com/bisiklet/13 &
wget -O epey14.html https://www.epey.com/bisiklet/14 &
wget -O epey15.html https://www.epey.com/bisiklet/15 &
wget -O epey16.html https://www.epey.com/bisiklet/16 &
wget -O epey17.html https://www.epey.com/bisiklet/17 &
wget -O epey18.html https://www.epey.com/bisiklet/18 &
wget -O epey19.html https://www.epey.com/bisiklet/19 &
wget -O epey20.html https://www.epey.com/bisiklet/20 &
wget -O epey21.html https://www.epey.com/bisiklet/21 &
wget -O epey22.html https://www.epey.com/bisiklet/22 &
wget -O epey23.html https://www.epey.com/bisiklet/23 &
wget -O epey24.html https://www.epey.com/bisiklet/24 &
wget -O epey25.html https://www.epey.com/bisiklet/25 &
wget -O epey26.html https://www.epey.com/bisiklet/26 &
wget -O epey27.html https://www.epey.com/bisiklet/27 &
wget -O epey28.html https://www.epey.com/bisiklet/28 &
wget -O epey29.html https://www.epey.com/bisiklet/29 &
wget -O epey30.html https://www.epey.com/bisiklet/30 &
wget -O epey31.html https://www.epey.com/bisiklet/31 &
wget -O epey32.html https://www.epey.com/bisiklet/32 &
wget -O epey33.html https://www.epey.com/bisiklet/33 &
wget -O epey34.html https://www.epey.com/bisiklet/34 &
wget -O epey35.html https://www.epey.com/bisiklet/35 &
wget -O epey36.html https://www.epey.com/bisiklet/36 &
wget -O epey37.html https://www.epey.com/bisiklet/37 &
wget -O epey38.html https://www.epey.com/bisiklet/38 &
wget -O epey39.html https://www.epey.com/bisiklet/39 &
wget -O epey40.html https://www.epey.com/bisiklet/40 &
wget -O epey41.html https://www.epey.com/bisiklet/41 &
wget -O epey42.html https://www.epey.com/bisiklet/42 &
wget -O epey43.html https://www.epey.com/bisiklet/43 &
wget -O epey44.html https://www.epey.com/bisiklet/44 &
wget -O epey45.html https://www.epey.com/bisiklet/45 &
wget -O epey46.html https://www.epey.com/bisiklet/46 &
wget -O epey47.html https://www.epey.com/bisiklet/47 &
wget -O epey48.html https://www.epey.com/bisiklet/48 &
wget -O epey49.html https://www.epey.com/bisiklet/49 &
wget -O epey50.html https://www.epey.com/bisiklet/50 &
wget -O epey51.html https://www.epey.com/bisiklet/51 &
wget -O epey52.html https://www.epey.com/bisiklet/52 &
wget -O epey53.html https://www.epey.com/bisiklet/53 &
wget -O epey54.html https://www.epey.com/bisiklet/54 &
wget -O epey55.html https://www.epey.com/bisiklet/55 &
wget -O epey56.html https://www.epey.com/bisiklet/56 &
wget -O epey57.html https://www.epey.com/bisiklet/57 &
wget -O epey58.html https://www.epey.com/bisiklet/58 &
wget -O epey59.html https://www.epey.com/bisiklet/59 &
wget -O epey60.html https://www.epey.com/bisiklet/60 &
wget -O epey61.html https://www.epey.com/bisiklet/61 &
wget -O epey62.html https://www.epey.com/bisiklet/62 &
wget -O epey63.html https://www.epey.com/bisiklet/63 &
wget -O epey64.html https://www.epey.com/bisiklet/64 &
wget -O epey65.html https://www.epey.com/bisiklet/65 &
wget -O epey66.html https://www.epey.com/bisiklet/66 &
wget -O epey67.html https://www.epey.com/bisiklet/67 &
wget -O epey68.html https://www.epey.com/bisiklet/68 &
wget -O epey69.html https://www.epey.com/bisiklet/69 &
wget -O epey70.html https://www.epey.com/bisiklet/70 &
wget -O epey71.html https://www.epey.com/bisiklet/71 &
wget -O epey72.html https://www.epey.com/bisiklet/72 &
wget -O epey73.html https://www.epey.com/bisiklet/73 &